In [1]:
import pandas as pd
df = pd.read_csv("tshirts.csv")
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [3]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799.0,40.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lan███rk ███ine█████████t L███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41███42/███bla█████████ pa███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599.0,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621███ 6n███ kh█████████zia███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199.0,50.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Fer███id,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15███ SH███MAR█████████RK ███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999.0,61.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299.0,61.0,"""₹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [5]:
df.shape

(39, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [9]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              39 non-null     int64
 1   title                   39 non-null     object
 2   product_description     39 non-null     object
 3   rating                  39 non-null     float64
 4   ratings_count           39 non-null     int64
 5   initial_price           39 non-null     float64
 6   discount                32 non-null     float64
 7   final_price             39 non-null     object
 8   currency                39 non-null     object
 9   images                  39 non-null     object
 10  delivery_options        39 non-null     object
 11  product_details         39 non-null     object
 12  breadcrumbs             39 non-null     object
 13  product_specifications  39 non-null     object
 14  amount_of_stars         39 non-null     object
 15  what_customers_said     30 non-null     object
 16  seller_name             18 non-null     object
 17  sizes                   39 non-null     object
 18  videos                  10 non-null     object
 19  seller_information      18 non-null     object
 20  variations              14 non-null     object
 21  best_offer              39 non-null     object
 22  more_offers             39 non-null     object
 23  category                39 non-null     object
dtypes: float64(3), int64(2), object(19)
memory usage: 7.4+ KB

In [13]:
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,True,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
5,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,True,True,False,False,False
6,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,True,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,True,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,True,False,False,False
12,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,True,True,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,True,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,True,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,True,False,False,False
17,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,True,True,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,True,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,True,False,False,False
21,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,True,True,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,True,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [15]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   7
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        9
seller_name               21
sizes                      0
videos                    29
seller_information        21
variations                25
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [78]:
df["seller_name"] = df["seller_name"].fillna(df["seller_name"].mode()[0])

In [80]:
df["what_customers_said"] = df["what_customers_said"].fillna(df["what_customers_said"].mode()[0])

In [86]:
df["seller_information"] = df["seller_information"].fillna(df["seller_information"].mode()[0])

In [88]:
df["variations"] = df["variations"].fillna(df["variations"].mode()[0])

In [90]:
df.head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_percent
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.276615
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,40.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.449388
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,40.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.004004
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.094631
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts,3.441802
5,8901821,UNDER ARMOUR,Men Charcoal Grey Big Logo SS Printed T-shirt,4.3,64,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/890...,...,"[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-8901821""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,2.001001
6,919032,Roadster,Off-White Black Striped Speckled Pure Cotton ...,3.8,641,899.0,40.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/919...,...,"[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...","[""rw-919032_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.449388
7,18817326,Tommy Hilfiger,Men Beige & Navy Blue Striped Pure Cotton T-shirt,4.4,58,2799.0,40.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.03in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,1.429082
8,8426447,WROGN,Men Navy Blue Striped Henley Neck T-shirt,4.2,514,1599.0,50.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/842...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""37.25in"",""value_name"":""C...","[""rw-8426447_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,3.126954
9,20355284,Roadster,The Life Co. Round Neck Raglan Sleeves Typogr...,4.2,74,999.0,53.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,5.305305

In [92]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        0
seller_name                0
sizes                      0
videos                    29
seller_information         0
variations                 0
best_offer                 0
more_offers                0
category                   0
discount_percent           0
dtype: int64

In [94]:
df["discount"] = df["discount"].fillna(df["discount"].mean())

In [96]:
df.dropna()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_percent
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,40.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.449388
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,40.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.004004
5,8901821,UNDER ARMOUR,Men Charcoal Grey Big Logo SS Printed T-shirt,4.3,64,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/890...,...,"[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-8901821""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,2.001001
6,919032,Roadster,Off-White Black Striped Speckled Pure Cotton ...,3.8,641,899.0,40.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/919...,...,"[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...","[""rw-919032_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.449388
8,8426447,WROGN,Men Navy Blue Striped Henley Neck T-shirt,4.2,514,1599.0,50.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/842...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""37.25in"",""value_name"":""C...","[""rw-8426447_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,3.126954
11,9213113,Roadster,The Lifestyle Co Men White Printed Round Neck...,4.1,994,799.0,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/921...,...,"[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-9213113_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,6.257822
12,13511732,Puma,Men Black Solid Run Fav 1/4 Zip T-Shirt,4.4,167,3999.0,40.0,"""₹3,999.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.65in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,1.000250
17,13502414,Puma,Men Navy Blue & White Performance Cat Printed ...,4.3,327,1499.0,40.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""36.61in"",""value_name"":""...","[""rw-13502414_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,2.668446
18,13621134,Roadster,The Lifestyle Co Men Rust Brown Solid Appliqu...,4.1,312,1399.0,50.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,3.573981
33,12953958,Allen Solly,Men Maroon Solid Polo Collar Pure Cotton T-shirt,4.4,409,999.0,40.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"[{""percentage"":""96"",""value_name"":""Fit, Just Ri...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...","[""rw-12953958_cae700"",""https://videos.myntasse...","Gro███ Fl███, N█████████old███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts,4.004004

In [98]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_percent
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.276615
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,40.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.449388
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,40.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.004004
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.094631
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts,3.441802

In [100]:
df[["initial_price","final_price"]]

    initial_price  final_price
0          1099.0  "₹1,099.00"
1           899.0    "₹899.00"
2           999.0    "₹999.00"
3          1099.0  "₹1,099.00"
4          1598.0    "₹719.00"
5          1999.0  "₹1,999.00"
6           899.0    "₹899.00"
7          2799.0  "₹2,799.00"
8          1599.0  "₹1,599.00"
9           999.0    "₹999.00"
10         1999.0  "₹1,999.00"
11          799.0    "₹799.00"
12         3999.0  "₹3,999.00"
13          999.0    "₹999.00"
14          599.0    "₹599.00"
15         1699.0  "₹1,699.00"
16         1399.0  "₹1,399.00"
17         1499.0  "₹1,499.00"
18         1399.0  "₹1,399.00"
19         1499.0  "₹1,499.00"
20          899.0    "₹674.00"
21         1199.0  "₹1,199.00"
22          899.0    "₹404.00"
23         1995.0    "₹578.00"
24         2998.0  "₹1,229.00"
25         1399.0    "₹699.00"
26         1399.0    "₹549.00"
27          699.0    "₹293.00"
28          835.0    "₹835.00"
29         1665.0    "₹499.00"
30         3998.0    "₹799.00"
31         1099.0    "₹384.00"
32         1799.0    "₹359.00"
33          999.0    "₹599.00"
34          799.0    "₹479.00"
35         1599.0    "₹671.00"
36         1199.0    "₹599.00"
37          999.0    "₹389.00"
38         1299.0    "₹506.00"

In [102]:
filtered_df = df[df["initial_price"]>1000.0]

In [104]:
filtered_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_percent
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.276615
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.094631
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts,3.441802
5,8901821,UNDER ARMOUR,Men Charcoal Grey Big Logo SS Printed T-shirt,4.3,64,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/890...,...,"[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-8901821""]",10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,2.001001
7,18817326,Tommy Hilfiger,Men Beige & Navy Blue Striped Pure Cotton T-shirt,4.4,58,2799.0,40.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.03in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,1.429082

In [106]:
df.duplicated().sum()

0

In [108]:
print(df["discount"])

0     47.0
1     40.0
2     40.0
3     45.0
4     55.0
5     40.0
6     40.0
7     40.0
8     50.0
9     53.0
10    40.0
11    50.0
12    40.0
13    60.0
14    30.0
15    40.0
16    73.0
17    40.0
18    50.0
19    30.0
20    25.0
21    40.0
22    55.0
23    71.0
24    59.0
25    53.0
26    60.0
27    58.0
28    25.0
29    70.0
30    80.0
31    65.0
32    80.0
33    40.0
34    40.0
35    58.0
36    50.0
37    61.0
38    61.0
Name: discount, dtype: float64

In [110]:
df.duplicated().sum()

0

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              39 non-null     int64
 1   title                   39 non-null     object
 2   product_description     39 non-null     object
 3   rating                  39 non-null     float64
 4   ratings_count           39 non-null     int64
 5   initial_price           39 non-null     float64
 6   discount                39 non-null     float64
 7   final_price             39 non-null     object
 8   currency                39 non-null     object
 9   images                  39 non-null     object
 10  delivery_options        39 non-null     object
 11  product_details         39 non-null     object
 12  breadcrumbs             39 non-null     object
 13  product_specifications  39 non-null     object
 14  amount_of_stars         39 non-null     object
 15  what_customers_said     39 non-null     object
 16  seller_name             39 non-null     object
 17  sizes                   39 non-null     object
 18  videos                  10 non-null     object
 19  seller_information      39 non-null     object
 20  variations              39 non-null     object
 21  best_offer              39 non-null     object
 22  more_offers             39 non-null     object
 23  category                39 non-null     object
 24  discount_percent        39 non-null     float64
dtypes: float64(4), int64(2), object(19)
memory usage: 7.7+ KB

In [114]:
df[["initial_price","discount","final_price"]].head()

   initial_price  discount  final_price
0         1099.0      47.0  "₹1,099.00"
1          899.0      40.0    "₹899.00"
2          999.0      40.0    "₹999.00"
3         1099.0      45.0  "₹1,099.00"
4         1598.0      55.0    "₹719.00"

In [116]:
df["discount_percent"] = (df["discount"]/df["initial_price"])*100

In [118]:
df["discount_percent"].head()

0    4.276615
1    4.449388
2    4.004004
3    4.094631
4    3.441802
Name: discount_percent, dtype: float64

In [120]:
df.head(2)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_percent
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.276615
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,40.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,4.449388

In [122]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'discount_percent'],
      dtype='object')

In [126]:
df.to_csv("cleaned_tshirts.csv",index=False)

In [128]:
print("Cleaned Dataset")

Cleaned Dataset